name: build
on:
  push:
    branches:
      - master

jobs:
  gradle-action-detection:
    runs-on: ubuntu-latest
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.7.2
        with:
          gradle-project-path: .
          gradle-build-module:
          use-gradlew: true
